### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by coodix** [skolodyazhnyy/amqp-bridge#1]
Hello @skolodyazhnyy !

I was looking such functionality and found this repository.

1. Could you please clarify terms of usage of your project?
2. Do you use it on production? Is it stable?
3. Is it better than rabbitmq-cli-consumer from your point of view?
4. Could you please add short readme with instructions of how to build, install and use it?

**Comment by skolodyazhnyy** [comment]
Hi @coodix 

The idea I have tried here is to build a bridge between AMQP Server and PHPFPM server. AMQP messages supposed to be translated into FPM Requests and then processed in the way similar to processing HTTP Request, then FPM response meant to be translated to ACK/NACK for the message. 

This repository is just a sandbox/playground where I tried to see how hard could it be to build such thing. It seems to be quite straight forward as all libraries are available for golang and all you need to do is just wire them up with little logic.

I'm currently using https://github.com/ricbra/rabbitmq-cli-consumer and it's enough for performance requirements I have at the moment.

I probably will start developing idea of amqp-bridge when performance of rabbitmq-cli-consumer become insufficient for me.

**Comment by coodix** [comment]
@skolodyazhnyy,  I will try then rabbitmq-cli-consumer too.

Thanks for clarification!
